# Generated by Django 4.0 on 2021-12-27 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_topic_post_user_comment_post_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
